import {test} from "node:test";import {strict as assert} from "node:assert";import {queueGuard} from "../src/queue-guard.js";
function fixture(pods=[{id:"newpod",name:"outdoor_silver_sparrow"}]){const store=new Map();let mutations=0;const env={WATCHDOG_AUTO_ARM:"yes",RUNPOD_API_KEY:"mock",WATCHDOG_EXPECTED_POD_NAME:"outdoor_silver_sparrow",WATCHDOG_STATE:{get:async k=>JSON.parse(store.get(k)||"null"),put:async(k,v)=>{store.set(k,v)}}};const api=async(q)=>{if(q.includes("podStop")){mutations++;pods=pods.map(p=>({...p,desiredStatus:"EXITED"}));return {podStop:true}}return {myself:{pods}}};return {env,api,store,get mutations(){return mutations}};}
test("off by default",async()=>assert.equal((await queueGuard({},0)).status,"disabled"));
test("waiting without Pod",async()=>{const f=fixture([]);assert.equal((await queueGuard(f.env,0,f.api)).status,"waiting_for_pod")});
test("never protects ambiguous or unrelated pods",async()=>{for(const pods of [[{id:"x",name:"other"}],[{id:"x",name:"outdoor_silver_sparrow"},{id:"y",name:"other"}]]){const f=fixture(pods);assert.equal((await queueGuard(f.env,0,f.api)).status,"identity_ambiguous");assert.equal(f.mutations,0)}});
test("stores first observation, stops after five minutes and verifies",async()=>{const f=fixture();assert.equal((await queueGuard(f.env,1000,f.api)).status,"protected_timer_started");assert.equal((await queueGuard(f.env,300999,f.api)).status,"protected_waiting");assert.equal(f.mutations,0);assert.equal((await queueGuard(f.env,301000,f.api)).status,"stopped_verified");assert.equal(f.mutations,1)});
test("rejects missing persistent storage",async()=>{const f=fixture();delete f.env.WATCHDOG_STATE;await assert.rejects(queueGuard(f.env,0,f.api),/configuration invalid/)});
test("rejects changed identity",async()=>{const f=fixture();await queueGuard(f.env,1000,f.api);await assert.rejects(queueGuard(f.env,301000,async()=>({myself:{pods:[{id:"newpod",name:"other"}]}})),/identity changed/)});

test("API query failure never starts timer",async()=>{const f=fixture();await assert.rejects(queueGuard(f.env,1000,async()=>{throw Error("network offline")}),/network offline/);assert.equal(f.store.size,0)});
test("explicit termination rejection fails and keeps retry state",async()=>{const f=fixture();await queueGuard(f.env,1000,f.api);const reject=async q=>q.includes("podStop")?{podStop:false}:{myself:{pods:[{id:"newpod",name:"outdoor_silver_sparrow"}]}};await assert.rejects(queueGuard(f.env,301000,reject),/rejected stop/);assert.equal(f.store.size,1)});
test("unverified stop fails and retains target",async()=>{const f=fixture();await queueGuard(f.env,1000,f.api);const noDelete=async q=>q.includes("podStop")?{podStop:true}:{myself:{pods:[{id:"newpod",name:"outdoor_silver_sparrow"}]}};await assert.rejects(queueGuard(f.env,301000,noDelete),/Stop unverified/);assert.equal(f.store.size,1)});
test("saved ID never switches to another matching Pod",async()=>{const f=fixture();await queueGuard(f.env,1000,f.api);const changed=async()=>({myself:{pods:[{id:"otherpod",name:"outdoor_silver_sparrow"}]}});assert.equal((await queueGuard(f.env,301000,changed)).status,"pod_absent");assert.equal(f.mutations,0)});
test("bad persisted state prevents termination",async()=>{const f=fixture();f.store.set("protected-pod-v1",JSON.stringify({podId:"invalid id",deadline:0}));await assert.rejects(queueGuard(f.env,301000,f.api),/Invalid persisted/);assert.equal(f.mutations,0)});

test("already stopped Pod is not enrolled for auto-stop",async()=>{const f=fixture([{id:"newpod",name:"outdoor_silver_sparrow",desiredStatus:"EXITED"}]);assert.equal((await queueGuard(f.env,1000,f.api)).status,"identity_ambiguous");assert.equal(f.store.size,0);assert.equal(f.mutations,0)});
test("saved stopped Pod is never stopped twice",async()=>{const f=fixture();await queueGuard(f.env,1000,f.api);const stopped=async()=>({myself:{pods:[{id:"newpod",name:"outdoor_silver_sparrow",desiredStatus:"EXITED"}]}});assert.equal((await queueGuard(f.env,301000,stopped)).status,"already_stopped");assert.equal(f.mutations,0)});
test("missing stop acceptance fails closed",async()=>{const f=fixture();await queueGuard(f.env,1000,f.api);const api=async q=>q.includes("podStop")?{}:{myself:{pods:[{id:"newpod",name:"outdoor_silver_sparrow"}]}};await assert.rejects(queueGuard(f.env,301000,api),/rejected stop/)});
